package meine.app;

import meine.util.AuthenticatorRealm;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Query;
import meine.models.Gebruiker;
import meine.util.MyDb;
import meine.models.Rollen;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import meine.util.Encrypter;

/**
 *
 * @author Meine Toonen
 */
public class Beginscherm extends javax.swing.JFrame {

    private AuthenticatorRealm realm;
    private static final Log log = LogFactory.getLog(Beginscherm.class);

    /** Creates new form Beginscherm */
    public Beginscherm() {
        // addWindowListener(Opstart.getWindowManager());
        initComponents();
        this.setLocationRelativeTo(null);
        realm = AuthenticatorRealm.getInstance();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        leraar = new javax.swing.JButton();
        beheerder = new javax.swing.JButton();
        leerling = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        annuleren = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        uitloggen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        logoPanel1 = new meine.app.LogoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keuzetest");

        jPanel2.setBackground(new java.awt.Color(252, 220, 147));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 170, 110));
        jLabel1.setText("Keuzetest");

        leraar.setText("Leraar");
        leraar.setEnabled(false);
        leraar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leraarActionPerformed(evt);
            }
        });

        beheerder.setText("Beheerder");
        beheerder.setEnabled(false);
        beheerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beheerderActionPerformed(evt);
            }
        });

        leerling.setText("Leerling");
        leerling.setEnabled(false);
        leerling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerlingActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Versie 0.7");

        jLabel3.setLabelFor(username);
        jLabel3.setText("Gebruikersnaam");

        jLabel4.setLabelFor(password);
        jLabel4.setText("Wachtwoord");

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });

        login.setText("Inloggen");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        annuleren.setText("Annuleren");
        annuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerenActionPerformed(evt);
            }
        });

        uitloggen.setText("Uitloggen");
        uitloggen.setEnabled(false);
        uitloggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uitloggenActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Made by Meine Toonen");

        javax.swing.GroupLayout logoPanel1Layout = new javax.swing.GroupLayout(logoPanel1);
        logoPanel1.setLayout(logoPanel1Layout);
        logoPanel1Layout.setHorizontalGroup(
            logoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        logoPanel1Layout.setVerticalGroup(
            logoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(login))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(annuleren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uitloggen)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(logoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(beheerder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leerling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leraar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(beheerder)
                        .addGap(18, 18, 18)
                        .addComponent(leraar))
                    .addComponent(logoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(leerling)
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(username))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(annuleren)
                    .addComponent(uitloggen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beheerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beheerderActionPerformed
        GebruikersBeheer gb = new GebruikersBeheer();
    }//GEN-LAST:event_beheerderActionPerformed

    private void leraarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leraarActionPerformed
        Leerkrachten lk = new Leerkrachten();
    }//GEN-LAST:event_leraarActionPerformed

    private void leerlingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerlingActionPerformed
        LeerlingTesten llt = new LeerlingTesten();
    }//GEN-LAST:event_leerlingActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        login();
    }//GEN-LAST:event_loginActionPerformed

    private void annulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerenActionPerformed
        realm.nullifyAuthentication();
        enableButtons();
    }//GEN-LAST:event_annulerenActionPerformed

    private void uitloggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uitloggenActionPerformed
        realm.nullifyAuthentication();
        enableButtons();
        status.setText("Uitgelogd");
    }//GEN-LAST:event_uitloggenActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        if (evt.getKeyChar() == evt.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_passwordKeyReleased

    private void enableButtons() {
        if (realm.getGebruiker() != null) {
            if (realm.isUserInRole(Rollen.BEHEERDER)) {
                beheerder.setEnabled(true);
                leraar.setEnabled(true);
                leerling.setEnabled(true);
            }

            if (realm.isUserInRole(Rollen.LERAAR)) {
                leraar.setEnabled(true);
                leerling.setEnabled(true);
            }

            if (realm.isUserInRole(Rollen.LEERLING)) {
                leerling.setEnabled(true);
            }
            login.setEnabled(false);
            annuleren.setEnabled(false);
            username.setEnabled(false);
            password.setEnabled(false);
            password.setText("");
            uitloggen.setEnabled(true);
            status.setText("Ingelogd");
        } else {
            beheerder.setEnabled(false);
            leraar.setEnabled(false);
            leerling.setEnabled(false);

            login.setEnabled(true);
            annuleren.setEnabled(true);
            username.setEnabled(true);
            password.setEnabled(true);
            username.setText("");
            password.setText("");
            uitloggen.setEnabled(false);
        }
    }

    private void login() {
        String user = username.getText();
        char[] pass = password.getPassword();
        String passw = new String(pass);
        EntityManager em = MyDb.getThreadEntityManager();
        EntityTransaction transaction = em.getTransaction();
        try {
            transaction.begin();

            Query q = em.createQuery("FROM Gebruiker g WHERE naam = :user").setParameter("user", user);
            Gebruiker gebruiker = (Gebruiker) q.getSingleResult();
            String encryptedPass = Encrypter.getHexSha1(gebruiker.getSalt(), passw);
            if (encryptedPass.equalsIgnoreCase(gebruiker.getWachtwoord())) {
                transaction.commit();
                realm.setGebruiker(gebruiker);
            } else {
                status.setText("Gebruikersnaam en/of wachtwoord komen niet overeen.");
                realm.nullifyAuthentication();
            }
        } catch (Exception e) {
            status.setText("Gebruikersnaam en/of wachtwoord komen niet overeen.");
            realm.nullifyAuthentication();
            log.error(e.getMessage());
            if (transaction.isActive()) {
                transaction.rollback();

            }
        } finally {
            if (transaction.isActive()) {
                transaction.commit();
            }
        }
        enableButtons();
    }

    /*private void openLogin(Rollen forward) {
    Login l = new Login();
    l.setForward(forward);
    //  this.setVisible(false);
    //   this.dispose();
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuleren;
    private javax.swing.JButton beheerder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton leerling;
    private javax.swing.JButton leraar;
    private javax.swing.JButton login;
    private meine.app.LogoPanel logoPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel status;
    private javax.swing.JButton uitloggen;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
