/*
 * KeuzeMomentTwoPanel.java
 *
 * Created on 28-aug-2011, 15:24:02
 */
package meine.app;

import java.util.Set;
import meine.models.KeuzeMoment;
import meine.models.KeuzeMomentFoto;
import meine.util.Plaats;

/**
 *
 * @author Meine Toonen
 */
public class KeuzeMomentFourPanel extends javax.swing.JPanel {

    private KeuzeMoment keuzemoment = null;

    /** Creates new form KeuzeMomentTwoPanel */
    public KeuzeMomentFourPanel() {
        initComponents();
    }

    public void setKeuzemoment(KeuzeMoment km) {
        this.keuzemoment = km;
        populateForm();
    }

    private void populateForm() {
        nummer.setText("" + (keuzemoment.getPlek() + 1));
        tijd.setText("" + keuzemoment.getTijd());
        Set<KeuzeMomentFoto> fotos = keuzemoment.getFotos();
        KeuzeMomentFoto[] kmfs = fotos.toArray(new KeuzeMomentFoto[0]);

        positionFoto(kmfs[0]);
        positionFoto(kmfs[1]);
        positionFoto(kmfs[2]);
        positionFoto(kmfs[3]);
    }

    private void positionFoto(KeuzeMomentFoto kmf) {
        String fotoPlek = kmf.getPositie().toString();
        if (fotoPlek.equals(Plaats.LINKSBOVEN.toString())) {
            linksboven.setFoto(kmf);
            if (keuzemoment.getKeuze() == kmf) {
                linksboven.setHatch(true);
            }
        } else if (fotoPlek.equals(Plaats.RECHTSBOVEN.toString())) {
            rechtsboven.setFoto(kmf);
            if (keuzemoment.getKeuze() == kmf) {
                rechtsboven.setHatch(true);
            }
        } else if (fotoPlek.equals(Plaats.LINKSONDER.toString())) {
            linksonder.setFoto(kmf);
            if (keuzemoment.getKeuze() == kmf) {
                linksonder.setHatch(true);
            }
        } else if (fotoPlek.equals(Plaats.RECHTSONDER.toString())) {
            rechtsonder.setFoto(kmf);
            if (keuzemoment.getKeuze() == kmf) {
                rechtsonder.setHatch(true);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nummer = new javax.swing.JLabel();
        linksboven = new meine.app.KeuzeMomentFotoPanel();
        rechtsboven = new meine.app.KeuzeMomentFotoPanel();
        jLabel1 = new javax.swing.JLabel();
        tijd = new javax.swing.JLabel();
        linksonder = new meine.app.KeuzeMomentFotoPanel();
        rechtsonder = new meine.app.KeuzeMomentFotoPanel();

        setBackground(new java.awt.Color(252, 220, 147));

        linksboven.setPreferredSize(new java.awt.Dimension(185, 214));

        javax.swing.GroupLayout linksbovenLayout = new javax.swing.GroupLayout(linksboven);
        linksboven.setLayout(linksbovenLayout);
        linksbovenLayout.setHorizontalGroup(
            linksbovenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        linksbovenLayout.setVerticalGroup(
            linksbovenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        rechtsboven.setPreferredSize(new java.awt.Dimension(190, 214));

        javax.swing.GroupLayout rechtsbovenLayout = new javax.swing.GroupLayout(rechtsboven);
        rechtsboven.setLayout(rechtsbovenLayout);
        rechtsbovenLayout.setHorizontalGroup(
            rechtsbovenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        rechtsbovenLayout.setVerticalGroup(
            rechtsbovenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        jLabel1.setText("Tijd:");

        javax.swing.GroupLayout linksonderLayout = new javax.swing.GroupLayout(linksonder);
        linksonder.setLayout(linksonderLayout);
        linksonderLayout.setHorizontalGroup(
            linksonderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        linksonderLayout.setVerticalGroup(
            linksonderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout rechtsonderLayout = new javax.swing.GroupLayout(rechtsonder);
        rechtsonder.setLayout(rechtsonderLayout);
        rechtsonderLayout.setHorizontalGroup(
            rechtsonderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        rechtsonderLayout.setVerticalGroup(
            rechtsonderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nummer)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(linksonder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(linksboven, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rechtsboven, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(rechtsonder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(tijd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nummer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(linksboven, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(rechtsboven, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rechtsonder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(linksonder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tijd))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private meine.app.KeuzeMomentFotoPanel linksboven;
    private meine.app.KeuzeMomentFotoPanel linksonder;
    private javax.swing.JLabel nummer;
    private meine.app.KeuzeMomentFotoPanel rechtsboven;
    private meine.app.KeuzeMomentFotoPanel rechtsonder;
    private javax.swing.JLabel tijd;
    // End of variables declaration//GEN-END:variables
}
