package meine.app;

import meine.util.Opstart;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author Meine Toonen
 */
public class LogoPanel extends javax.swing.JPanel {

    private BufferedImage image;
    private static final Log log = LogFactory.getLog(LogoPanel.class);

    /** Creates new form ImagePanel2 */
    public LogoPanel() {
        initComponents();
        try {
            image = ImageIO.read(Opstart.f);
        } catch (IOException ex) {
            log.error(ex);
        }
    }

    @Override
    public void paintComponent(Graphics g) {

        g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), null);
        //g.drawImage(image, 0, 0, null); // see javadoc for more info on the parameters

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
